//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Envios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbArticulos
    {
        public int art_ID { get; set; }
        public string art_Descripcion { get; set; }
        public int fab_ID { get; set; }
        public int art_Stock { get; set; }
        public int art_UsuarioCreador { get; set; }
        public System.DateTime art_FechaCreacion { get; set; }
        public Nullable<int> art_UsuarioMod { get; set; }
        public Nullable<System.DateTime> art_FechaMod { get; set; }
        public bool art_Estado { get; set; }
    
        public virtual tbFabricas tbFabricas { get; set; }
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
    }
}
