//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Envios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCargos
    {
        public int carg_Id { get; set; }
        public string carg_Description { get; set; }
        public int rep_UsuarioCreador { get; set; }
        public System.DateTime rep_FechaCreacion { get; set; }
        public Nullable<int> rep_UsuarioMod { get; set; }
        public Nullable<System.DateTime> rep_FechaMod { get; set; }
        public bool rep_Estado { get; set; }
    
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
    }
}
