//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Envios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbClientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbClientes()
        {
            this.tbDirecciones = new HashSet<tbDirecciones>();
        }
    
        public int client_ID { get; set; }
        public string client_Nombre { get; set; }
        public string client_Identidad { get; set; }
        public string client_EstadoCivil { get; set; }
        public string client_Sexo { get; set; }
        public string client_Telefono { get; set; }
        public string client_Saldo { get; set; }
        public string client_LimiteCredito { get; set; }
        public string client_Descuento { get; set; }
        public int client_UsuarioCreador { get; set; }
        public System.DateTime client_FechaCreacion { get; set; }
        public Nullable<int> client_UsuarioMod { get; set; }
        public Nullable<System.DateTime> client_FechaMod { get; set; }
        public bool client_Estado { get; set; }
    
        public virtual tbEstadosCiviles tbEstadosCiviles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDirecciones> tbDirecciones { get; set; }
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
    }
}
