//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Envios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbFabricas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbFabricas()
        {
            this.tbArticulos = new HashSet<tbArticulos>();
        }
    
        public int fab_ID { get; set; }
        public string fab_Descripcion { get; set; }
        public string fab_Telefono { get; set; }
        public int fab_UsuarioCreador { get; set; }
        public System.DateTime fab_FechaCreacion { get; set; }
        public Nullable<int> fab_UsuarioMod { get; set; }
        public Nullable<System.DateTime> fab_FechaMod { get; set; }
        public bool fab_Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbArticulos> tbArticulos { get; set; }
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
    }
}
