//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Envios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRolPantallas
    {
        public int rp_ID { get; set; }
        public Nullable<int> rp_RolID { get; set; }
        public Nullable<int> rp_PantallasID { get; set; }
    
        public virtual tblPantallas tblPantallas { get; set; }
        public virtual tblRoles tblRoles { get; set; }
    }
}
