//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Envios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPedidoDetalles
    {
        public int det_Id { get; set; }
        public int pedi_ID { get; set; }
        public int art_ID { get; set; }
        public int det_Cantidad { get; set; }
        public int det_UsuarioCrea { get; set; }
        public System.DateTime det_FechaCrea { get; set; }
        public Nullable<int> det_UsuModif { get; set; }
        public Nullable<System.DateTime> det_FechaModif { get; set; }
        public Nullable<bool> det_Estado { get; set; }
    
        public virtual tbPedidos tbPedidos { get; set; }
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
    }
}
