//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Envios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPedidos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbPedidos()
        {
            this.tbPedidoDetalles = new HashSet<tbPedidoDetalles>();
        }
    
        public int pedi_ID { get; set; }
        public string pedi_Code { get; set; }
        public int pedi_DireccionID { get; set; }
        public decimal pedi_CostoEnvio { get; set; }
        public int estv_Id { get; set; }
        public int emp_Id { get; set; }
        public System.DateTime pedi_Fecha { get; set; }
        public int pedi_UsuarioCreador { get; set; }
        public System.DateTime pedi_FechaCreacion { get; set; }
        public Nullable<int> pedi_UsuarioMod { get; set; }
        public Nullable<System.DateTime> pedi_FechaMod { get; set; }
        public bool pedi_Estado { get; set; }
    
        public virtual tbDirecciones tbDirecciones { get; set; }
        public virtual tbEstadoEnvios tbEstadoEnvios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbPedidoDetalles> tbPedidoDetalles { get; set; }
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
    }
}
