//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Envios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_INDEX_PEDIDOS_DETALLES
    {
        public int ID_PEDIDO { get; set; }
        public string ARTICULO { get; set; }
        public int CANTIDAD { get; set; }
    }
}
